### PR TITLE
docker network

### PR DESCRIPTION
**Pull request by lioramilbaum**
Work in Progress
The connection from Jenkins to Rabbitmq still not working when using the following values:
screen shot 2019-01-26 at 16 29 15
screen shot 2019-01-26 at 16 30 20

### CODE REVIEW

**Comment by bregman-arie** [comment]
Is there anything in rabbitmq log?

**Comment by lioramilbaum** [comment]
2019-01-26 13:49:20.244 [error] <0.1082.0> Error on AMQP connection <0.1082.0> (172.18.0.2:36300 -> 172.18.0.3:5672, state: starting):
PLAIN login refused: user 'jenkins' - invalid credentials

**Comment by bregman-arie** [comment]
Which part in Dpline creates the creds for Jenkins in RabbitMQ?

**Comment by lioramilbaum** [comment]
rabbitmq/Dockerfile

**Pull request closed without merging**
