### PR TITLE
Ansible role docker

### PR DESCRIPTION
**Pull request by lioramilbaum**
#27

### CODE REVIEW

**Comment by bregman-arie** [comment]
@lioramilbaum what about removing the current role?

**Comment by lioramilbaum** [comment]
@bregman-arie I did. The current role file is removed and is part of the PR.

**Comment by bregman-arie** [comment]
@lioramilbaum no, 'setup/roles/install_docker' is still there. this PR doesn't removes it

**Comment by bregman-arie** [comment]
Right, my bad

**Pull request merged**
